version: "3"
services:
  postgres:
    container_name: wallet_postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
  redis:
    container_name: wallet_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mailhog:
    container_name: wallet_mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  redis:
    driver: local
